sudo: required

git:
  depth: 10

addons:
  chrome: stable

language: node_js

node_js:
  - "10"
  - "8"

cache:
  directories:
  - $HOME/.npm
  - node_modules

stages:
  - name: build
    if: (tag NOT present)
  - name: build and publish
    if: (tag IS present)

jobs:
  include:
    - stage: build
      script:
        - xvfb-run npm run build:ci
    - stage: build and publish
      script:
        - xvfb-run npm run build:ci
      after_success:
        - npm run publish:ci
