sudo: required

git:
  depth: 10

addons:
  chrome: stable

language: node_js

node_js:
  - "10"
  - "8"

cache:
  directories:
  - $HOME/.npm
  - node_modules

jobs:
  include:
    - script: xvfb-run npm run build:ci
    # publish if script exists
    - if: (tag IS present)
      script: npm run publish:ci
