sudo: required

git:
  depth: 10

addons:
  chrome: stable

language: node_js

node_js:
  - "10"
  - "8"

cache:
  directories:
  - $HOME/.npm
  - node_modules

script:
  - xvfb-run npm run build:ci

after_script:
  - npm run test:publish

  if: (branch = master AND tag IS present)
    - npm run publish:ci
