sudo: required

git:
  depth: 10

addons:
  chrome: stable

language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
  - $HOME/.npm
  - node_modules

stages:
  - name: lint
  - name: compile
  - name: test
  - name: publish
    if: (branch = master AND tag IS present)


jobs:
  include:
    - stage: lint
      script: npm run lint

    - stage: compile
      script: npm run build

    - stage: test
      script: xvfb-run npm run test:ci
      after_script: npm run test:publish

    - stage: publish
      script: npm run publish:ci
