sudo: required

git:
  depth: 10

addons:
  chrome: stable

language: node_js

node_js:
  - "10"
  - "8"

cache:
  directories:
  - $HOME/.npm
  - node_modules

script: xvfb-run npm run build:ci

jobs:
  include:
    - stage: publish
      if: tag IS present
      script: echo "Publishing to npm ..."
      deploy:
        provider: script
        script: npm run publish:ci
